config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  #get 'home/index'
  root 'home#index'
  get 'home/about'

  post "/" => 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
	belongs_to :user
	validates :ticker, presence: true
	validates :ticker, format: {without: /\s/}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@api = StockQuote::Stock.new(api_key: 'pk_63eaa71493e04f1e91fbd7d466c44f70')
  	
  	if params[:ticker] == ""
  		@nothing = "No company was entered!"
  	elsif params[:ticker]
  		begin @stock = StockQuote::Stock.quote(params[:ticker])
  		rescue 
  		@error = "That stock symbol doesn't exist"
  		else 
  		p "No error"
  		ensure
  		p "Done"
  		end
   	 end
  end

  def about
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  def correct_user
    @ticker = current_user.stock.find_by(id: params[:id])
    redirect_to stocks_path, notice: "Not Authorized to edit this stock" if @ticker.nil?

  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:ticker, :string, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
	<div class="alert alert-warning alert-dismissible" role="alert">
  		<%= content_tag(:span, msg) %>
  		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>


<% end %>

app/views/home/_navbar.html.erb
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Stock App", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        	<%= link_to "About", home_about_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
            <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
          <%= link_to "Show Stocks", stocks_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
          <%= link_to "Add Stocks", new_stock_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
                <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %> 
                </li>
                <li class="nav-item">
                  <%= link_to "Login", new_user_session_path, class: "nav-link" %>
                </li>
          <% end %>
      

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-danger" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About me</h1>
<p>Hello World</p>

app/views/home/index.html.erb
<h1>Stocks</h1>

<%= form_tag root_path, :method => 'POST' do %>
	<%= text_field_tag 'ticker', nil, placeholder: "Enter Ticker Symbol", size: 50 %>
	<%= submit_tag 'Lookup' %>
<% end %>

<br/>

<% if @stock %>
	<%= @stock.company_name %><br/>
	<%= @stock.latest_price %><br/>
<% elsif @nothing %>
	<%= @nothing %>
<% end %>

<% if @error %>
	<%= @error %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Stock Market App</title>
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'home/navbar' %>

    <div class="container">
    <%= render 'home/flash' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.text_field :ticker %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, value: current_user.id, type: :hidden  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<table class="table table-striped table-bordered table-hover"  >
  <thead class="table-light">
    <tr>
      <th>Company</th>
      <th>Ticker</th>
      <th>Current Price</th>
      <th>Market Cap</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <% if stock.user_id == current_user.id %>

     <% if stock.ticker == "" %>
     <% @ticker.company_name = "N/A" %>
      <% @ticker.symbol = "N/A" %>
      <% @ticker.latest_price= "N/A" %>
      <% @ticker.market_cap= "N/A" %>


      <% elsif stock.ticker %>
      <% begin @ticker = StockQuote::Stock.quote(stock.ticker) %>
       <% rescue %>
      <% @ticker.company_name = "N/A" %>
      <% @ticker.symbol = "N/A" %>
      <% @ticker.latest_price= "N/A" %>
     <% else %>
     <% p "No error" %>
      <%  ensure %>
     <% p "Done" %>
    <% end %>
     <% end %>
       

        <tr>
          <td><%= link_to @ticker.company_name, stock %> </td>
          <td><%= @ticker.symbol %></td>
          <td>$<%= number_with_precision(@ticker.latest_price, :precision => 2, :delimiter => ',') %></td>
          <td>$<%= number_with_precision(@ticker.market_cap, :precision => 2, :delimiter => ',') %> </td>
          <td><center><%= link_to 'Edit', edit_stock_path(stock), class: "btn btn-primary" %></center></td>
          <td><center><%= link_to 'Destroy', stock, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p>
  <strong>Ticker:</strong>
  <%= @stock.ticker %>
</p>


<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>